name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 16777212

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        include:
          - platform: ubuntu-22.04
            artifact-path: target/release/fend
            artifact-platform-name: linux-x64
            env-command: ">> $GITHUB_ENV"

    runs-on: ubuntu-22.04

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

#       - name: Install Rust toolchain
#         uses: briansmith/actions-rs-toolchain@v1
#         with:
#           override: true
#           target: x86_64-unknown-linux-musl
#           toolchain: stable

#       - name: Overwrite build command env variable
#         shell: bash
#         run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build, get version
        run: |
          sudo apt update && sudo apt install -y musl-tools tree
          cargo build --locked --release --package fend --target x86_64-unknown-linux-musl
          echo "FEND_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages | .[0].version')" >> $GITHUB_ENV
          tree
          pwd
          ls cli


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fend-${{ env.FEND_VERSION }}-linux-x64
          path: target/release/fend
          if-no-files-found: error
